library: /Volumes/goose/beets/music.blb
directory: /Volumes/goose/beets
path_format: $artist/$album ($original_year)/$track $title
import:
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
ignore: .AppleDouble ._* *~ .DS_Store Thumbs.db
art_filename: cover
threaded: yes
color: yes
plugins: fetchart lyrics lastgenre web

paths:
    default: $albumartist/$album ($original_year)/$track $title
    singleton: singles/$artist - $title
    # comp: $genre/$album/$track $title
    # albumtype:soundtrack: Soundtracks/$album/$track $title

