library: /Users/lee/Music/beets/music.blb
directory: /Users/lee/Music/beets
path_format: $artist/$album ($original_year)/$track $title
import:
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
ui:
    color: yes
ignore: .AppleDouble ._* *~ .DS_Store Thumbs.db
art_filename: cover
threaded: yes
plugins: fetchart lastgenre web ftintitle

paths:
    default: $albumartist/$album ($original_year)/$track $title
    singleton: singles/$artist - $title
    # comp: $genre/$album/$track $title
    # albumtype:soundtrack: Soundtracks/$album/$track $title
fetchart:
    remote_priority: yes
    maxwidth: 1000
ftintitle:
    auto: yes
    format: (feat. {0})
